matrix:
  include:
    - stage: "Lint"
      language: node_js
      os: linux
      node_js: "8"
      script: cd src && npm run ci.tslint && cd ../demo && npm run ci.tslint
    - stage: "WebPack, Build and Test"
      os: osx
      env:
        - WebPack="iOS"
      osx_image: xcode10.0
      language: node_js 
      node_js: "8"
      jdk: oraclejdk8
      before_install: pip install six
      script: cd demo && npm run build.ci.iosOnly && npm i && tns build ios --bundle --env.uglify
    - language: android
      os: linux
      env:
        - WebPack="Android"
      jdk: oraclejdk8
      before_install: nvm install 8
      script: cd demo && npm run build.ci.plugin && npm i && tns build android --bundle --env.uglify --env.snapshot
    - language: android
      env: 
        - BuildAndroid="28"
      os: linux
      jdk: oraclejdk8
      before_install: nvm install stable
      script:
        - cd src && npm run clean.ci && npm run tsc && cd ../demo && tns build android
    - os: osx
      env: 
        - BuildiOS="12"
        - Xcode="10.0"
      osx_image: xcode10.0
      language: node_js 
      node_js: "8"
      jdk: oraclejdk8
      before_install: pip install six
      script: 
        - cd src && npm run clean.ci && npm run tsc && cd ../demo && tns build ios
    - os: linux
      language: android
      dist: precise
      sudo: required
      jdk: oraclejdk8
      before_script:
        - echo no | android create avd --force -n test -t android-21 -b armeabi-v7a
        - emulator -avd test -no-audio -no-window &
        - android-wait-for-emulator
      before_install:
        - nvm install 8
      script: cd src && npm run test.ci.android
    - os: osx
      language: node_js
      node_js: "8"
      jdk: oraclejdk8
      before_install: pip install six
      osx_image: xcode10.0
      script: cd src && npm run test.ci.ios
    - stage: "UI Tests"
    - os: linux
      env: 
        - Android="26"
      language: node_js
      node_js: "8"
      before_script:
         before_script:
        - echo no | android create avd --force -n Pixel_API_26 -t android-26 -b armeabi-v7a
      script:
        - npm i -g appium
        - cd demo && npm i && tns run build android && npm run e2e -- --runType android26
    - os: osx
      env: 
        - iOS="12.1"
        - Xcode="10.0"
      osx_image: xcode10.0
      language: node_js 
      node_js: "8"
      script: 
        - npm i -g appium
        - cd demo && npm i && tns run ios && npm run e2e -- --runType sim.iPhone6.121


android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.2
    - android-28
    - android-26
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-21
    - sys-img-x86-android-26

install:
    - echo no | npm install -g nativescript
    - tns usage-reporting disable
    - tns error-reporting disable